// ai-bootstrap/templates/starter/vue-element-plus-web/src/App.vue
<script setup lang="ts">
// @agent: codex
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuth } from './composables/useAuth'
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import { Briefcase, DataAnalysis, SwitchButton, User } from '@element-plus/icons-vue'

const { user, signOut } = useAuth()
const route = useRoute()
const router = useRouter()

const activeMenu = computed(() => (route.name === 'jobs' ? '/jobs' : '/'))
const pageTitle = computed(() => {
  if (route.name === 'jobs') return '岗位管理'
  if (route.name === 'login') return '登录'
  return '工作台'
})

function onLogout() {
  signOut()
  router.push('/login')
}
</script>

<template>
  <!-- Element Plus 官方 ConfigProvider：中文 locale 统一注入 -->
  <el-config-provider :locale="zhCn">
    <el-container class="app-shell">
      <el-aside width="220px" class="app-aside">
        <div class="brand">{{PROJECT_NAME}}</div>
        <el-menu :default-active="activeMenu" router>
          <el-menu-item index="/">
            <el-icon><DataAnalysis /></el-icon>
            <span>工作台</span>
          </el-menu-item>
          <el-menu-item index="/jobs">
            <el-icon><Briefcase /></el-icon>
            <span>岗位管理</span>
          </el-menu-item>
        </el-menu>
      </el-aside>
      <el-container>
        <el-header class="app-header">
          <div class="page-title">{{ pageTitle }}</div>
          <div class="user-area">
            <el-icon><User /></el-icon>
            <span class="user-name">{{ user?.name ?? '未登录' }}</span>
            <el-button link type="primary" @click="onLogout">
              <el-icon><SwitchButton /></el-icon>
              退出
            </el-button>
          </div>
        </el-header>
        <el-main class="app-main">
          <router-view />
        </el-main>
      </el-container>
    </el-container>
  </el-config-provider>
</template>

<style>
/* 全局布局使用 --el-* 语义令牌（tokens.css 定义），页面不散落魔法色值 */
.app-shell {
  min-height: 100vh;
}
.app-aside {
  background: var(--el-bg-color, #f6f8fc);
  border-right: 1px solid var(--el-border-color-lighter, #eef2f7);
}
.brand {
  padding: 20px 24px;
  font-size: 17px;
  font-weight: 700;
  color: var(--el-text-color-primary, #172033);
}
.app-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  background: var(--el-fill-color-blank, #ffffff);
  border-bottom: 1px solid var(--el-border-color-lighter, #eef2f7);
}
.page-title {
  font-size: 16px;
  font-weight: 600;
  color: var(--el-text-color-primary, #172033);
}
.user-area {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--el-text-color-regular, #475467);
}
.app-main {
  background: var(--el-bg-color-page, #f6f8fc);
}
</style>

// ai-bootstrap/templates/starter/react-shadcn-web/src/App.tsx
// @agent: codex
import { useState } from 'react'
import { BarChart3, Briefcase, LogOut, User } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { useAuth } from './hooks/useAuth'
import Dashboard from './views/Dashboard'
import Jobs from './views/Jobs'
import Login from './views/Login'

type ViewKey = 'dashboard' | 'jobs' | 'login'

const navItems = [
  { key: 'dashboard' as ViewKey, label: '工作台', icon: BarChart3 },
  { key: 'jobs' as ViewKey, label: '岗位管理', icon: Briefcase },
]

export default function App() {
  const [view, setView] = useState<ViewKey>('dashboard')
  const { user, signOut } = useAuth()
  const current: ViewKey = user ? view : 'login'

  return (
    <div className="flex min-h-screen bg-background">
      <aside className="flex w-56 shrink-0 flex-col border-r border-border bg-card">
        <div className="px-5 py-4 text-base font-semibold text-foreground">{'{{PROJECT_NAME}}'}</div>
        <nav className="flex flex-col gap-1 px-3">
          {navItems.map((item) => (
            <button
              key={item.key}
              onClick={() => setView(item.key)}
              className={
                current === item.key
                  ? 'flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground'
                  : 'flex items-center gap-2 rounded-md px-3 py-2 text-sm text-muted-foreground hover:bg-accent hover:text-accent-foreground'
              }
            >
              <item.icon className="size-4" />
              {item.label}
            </button>
          ))}
        </nav>
      </aside>
      <div className="flex min-w-0 flex-1 flex-col">
        <header className="flex h-14 shrink-0 items-center justify-end gap-3 border-b border-border bg-card px-6">
          <User className="size-4 text-muted-foreground" />
          <span className="text-sm text-muted-foreground">{user?.name ?? '未登录'}</span>
          {user && (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                signOut()
                setView('login')
              }}
            >
              <LogOut />
              退出
            </Button>
          )}
        </header>
        <main className="flex-1 p-4">
          {current === 'login' ? (
            <Login onSuccess={() => setView('dashboard')} />
          ) : current === 'jobs' ? (
            <Jobs />
          ) : (
            <Dashboard onManage={() => setView('jobs')} />
          )}
        </main>
      </div>
    </div>
  )
}
